#!/bin/sh

set -e
set -u

echo '0000:00:1a.0' | sudo tee /sys/bus/pci/drivers/ehci-pci/unbind > /dev/null
echo '0000:00:1a.0' | sudo tee /sys/bus/pci/drivers/ehci-pci/bind   > /dev/null

echo '0000:00:1d.0' | sudo tee /sys/bus/pci/drivers/ehci-pci/unbind > /dev/null
echo '0000:00:1d.0' | sudo tee /sys/bus/pci/drivers/ehci-pci/bind   > /dev/null

echo '0000:00:14.0' | sudo tee /sys/bus/pci/drivers/xhci_hcd/unbind > /dev/null
echo '0000:00:14.0' | sudo tee /sys/bus/pci/drivers/xhci_hcd/bind   > /dev/null
